'use strict';

const { validateBody } = require('../lib/validators');
const { formatCompanyProfile } = require('../lib/linkedin-formatters');

function deriveCompanyNameFromUrl(url) {
  if (!url) return 'Unknown Company';
  const match = url.match(/\/company\/([^/?#]+)/i);
  const slug = match ? match[1] : url.split('/').filter(Boolean).pop();
  if (!slug) return 'Unknown Company';
  const cleaned = slug.split(/[^\w]+/).filter(Boolean);
  if (!cleaned.length) return 'Unknown Company';
  return cleaned
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(' ');
}

module.exports = async function companyData(body, context = {}) {
  const { logger } = context;
  validateBody('company-data', body);

  const url = body.url;
  const companyName = body.companyName || deriveCompanyNameFromUrl(url);
  const createdYear = 2010 + (companyName.length % 10);

  const result = formatCompanyProfile({
    endpoint: 'company-data',
    url,
    companyName,
    companyWebsite:
      body.companyWebsite ||
      `https://www.${companyName.replace(/\s+/g, '').toLowerCase()}.example`,
    companyIndustry: body.companyIndustry || 'Information Technology & Services',
    companySize: body.companySize || '51-200 employees',
    companyFoundedYear: body.companyFoundedYear || createdYear,
    companyHeadquarters: body.companyHeadquarters || 'Unknown',
    followersCount: body.followersCount || Math.floor(1000 + companyName.length * 137),
    description:
      body.description ||
      `${companyName} is a sample LinkedIn company profile generated by the unified scraper.`,
  });

  if (logger && logger.debug) {
    logger.debug('company-data result built for', url);
  }

  return [result];
};