'use strict';

const { validateBody } = require('../lib/validators');
const { paginateArray } = require('../lib/pagination');
const { formatPost } = require('../lib/linkedin-formatters');

function generateSeed(url) {
  let hash = 0;
  for (let i = 0; i < url.length; i += 1) {
    hash = (hash * 31 + url.charCodeAt(i)) >>> 0;
  }
  return hash || 1;
}

function pseudoRandom(seed, index) {
  const x = Math.sin(seed + index * 409) * 10000;
  return x - Math.floor(x);
}

function buildPosts(url, total = 40) {
  const seed = generateSeed(url);
  const posts = [];
  const now = Date.now();

  for (let i = 0; i < total; i += 1) {
    const rnd = pseudoRandom(seed, i);
    const daysAgo = Math.floor(rnd * 180);
    const createdAt = new Date(now - daysAgo * 24 * 60 * 60 * 1000);
    const postId = `${seed}-c-${i}`;

    posts.push(
      formatPost({
        endpoint: 'company-posts',
        postId,
        postUrl: `${url}/posts/${postId}`,
        postText: `Sample company post #${i + 1} for ${url}, generated by the unified scraper.`,
        postMedia: [],
        postCreatedAt: createdAt.toISOString(),
        postTimestamp: createdAt.getTime(),
        likesCount: Math.floor(rnd * 800),
        commentsCount: Math.floor(rnd * 120),
        sharesCount: Math.floor(rnd * 80),
        authorUrl: url,
        authorType: 'company',
      })
    );
  }

  return posts;
}

module.exports = async function companyPosts(body, context = {}) {
  const { logger, defaults } = context;
  validateBody('company-posts', body);

  const url = body.url;
  const requestedPage = body.page || 1;
  const pageSize = defaults.pageSize || 10;

  const posts = buildPosts(url);
  const { items, pageInfo } = paginateArray(posts, requestedPage, pageSize);

  if (logger && logger.info) {
    logger.info(
      `company-posts for ${url} returned page ${pageInfo.page}/${pageInfo.totalPages} (${items.length} posts).`
    );
  }

  return items.map((item) => ({
    ...item,
    page: pageInfo.page,
  }));
};